# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChildWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChildDialog(object):
    def setupUi(self, ChildDialog):
        ChildDialog.setObjectName("ChildDialog")
        ChildDialog.resize(803, 529)
        ChildDialog.setFocusPolicy(QtCore.Qt.NoFocus)
        ChildDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label = QtWidgets.QLabel(ChildDialog)
        self.label.setGeometry(QtCore.QRect(450, 51, 131, 16))
        self.label.setMouseTracking(False)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setObjectName("label")
        self.totalTime_lineEdit = QtWidgets.QLineEdit(ChildDialog)
        self.totalTime_lineEdit.setEnabled(False)
        self.totalTime_lineEdit.setGeometry(QtCore.QRect(583, 51, 171, 21))
        self.totalTime_lineEdit.setObjectName("totalTime_lineEdit")
        self.label_2 = QtWidgets.QLabel(ChildDialog)
        self.label_2.setGeometry(QtCore.QRect(450, 93, 141, 16))
        self.label_2.setMouseTracking(False)
        self.label_2.setObjectName("label_2")
        self.workTime_lineEdit = QtWidgets.QLineEdit(ChildDialog)
        self.workTime_lineEdit.setEnabled(False)
        self.workTime_lineEdit.setGeometry(QtCore.QRect(583, 93, 171, 21))
        self.workTime_lineEdit.setObjectName("workTime_lineEdit")
        self.workDistance_lineEdit = QtWidgets.QLineEdit(ChildDialog)
        self.workDistance_lineEdit.setEnabled(False)
        self.workDistance_lineEdit.setGeometry(QtCore.QRect(583, 177, 171, 21))
        self.workDistance_lineEdit.setObjectName("workDistance_lineEdit")
        self.label_3 = QtWidgets.QLabel(ChildDialog)
        self.label_3.setGeometry(QtCore.QRect(450, 135, 121, 16))
        self.label_3.setObjectName("label_3")
        self.totalDistance_lineEdit = QtWidgets.QLineEdit(ChildDialog)
        self.totalDistance_lineEdit.setEnabled(False)
        self.totalDistance_lineEdit.setGeometry(QtCore.QRect(583, 135, 171, 21))
        self.totalDistance_lineEdit.setObjectName("totalDistance_lineEdit")
        self.label_4 = QtWidgets.QLabel(ChildDialog)
        self.label_4.setGeometry(QtCore.QRect(450, 177, 141, 16))
        self.label_4.setMouseTracking(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ChildDialog)
        self.label_5.setGeometry(QtCore.QRect(450, 219, 151, 16))
        self.label_5.setMouseTracking(False)
        self.label_5.setObjectName("label_5")
        self.area_lineEdit = QtWidgets.QLineEdit(ChildDialog)
        self.area_lineEdit.setEnabled(False)
        self.area_lineEdit.setGeometry(QtCore.QRect(583, 219, 171, 21))
        self.area_lineEdit.setObjectName("area_lineEdit")
        self.label_6 = QtWidgets.QLabel(ChildDialog)
        self.label_6.setGeometry(QtCore.QRect(450, 261, 90, 16))
        self.label_6.setObjectName("label_6")
        self.distanceRatio_lineEdit = QtWidgets.QLineEdit(ChildDialog)
        self.distanceRatio_lineEdit.setEnabled(False)
        self.distanceRatio_lineEdit.setGeometry(QtCore.QRect(583, 303, 171, 21))
        self.distanceRatio_lineEdit.setObjectName("distanceRatio_lineEdit")
        self.timeRatio_lineEdit = QtWidgets.QLineEdit(ChildDialog)
        self.timeRatio_lineEdit.setEnabled(False)
        self.timeRatio_lineEdit.setGeometry(QtCore.QRect(583, 261, 171, 21))
        self.timeRatio_lineEdit.setObjectName("timeRatio_lineEdit")
        self.label_7 = QtWidgets.QLabel(ChildDialog)
        self.label_7.setGeometry(QtCore.QRect(450, 303, 60, 16))
        self.label_7.setMouseTracking(False)
        self.label_7.setObjectName("label_7")
        self.ratio_lineEdit = QtWidgets.QLineEdit(ChildDialog)
        self.ratio_lineEdit.setEnabled(False)
        self.ratio_lineEdit.setGeometry(QtCore.QRect(583, 367, 171, 21))
        self.ratio_lineEdit.setObjectName("ratio_lineEdit")
        self.label_8 = QtWidgets.QLabel(ChildDialog)
        self.label_8.setGeometry(QtCore.QRect(450, 345, 158, 16))
        self.label_8.setMouseTracking(False)
        self.label_8.setObjectName("label_8")
        self.edgeMap_button = QtWidgets.QPushButton(ChildDialog)
        self.edgeMap_button.setGeometry(QtCore.QRect(471, 402, 93, 28))
        self.edgeMap_button.setObjectName("edgeMap_button")
        self.workMap_button = QtWidgets.QPushButton(ChildDialog)
        self.workMap_button.setGeometry(QtCore.QRect(583, 402, 93, 28))
        self.workMap_button.setObjectName("workMap_button")
        self.traMap_button = QtWidgets.QPushButton(ChildDialog)
        self.traMap_button.setGeometry(QtCore.QRect(700, 402, 93, 28))
        self.traMap_button.setObjectName("traMap_button")
        self.graphicsView = QtWidgets.QGraphicsView(ChildDialog)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 411, 491))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(ChildDialog)
        QtCore.QMetaObject.connectSlotsByName(ChildDialog)
        ChildDialog.setTabOrder(self.totalTime_lineEdit, self.workTime_lineEdit)
        ChildDialog.setTabOrder(self.workTime_lineEdit, self.totalDistance_lineEdit)
        ChildDialog.setTabOrder(self.totalDistance_lineEdit, self.workDistance_lineEdit)
        ChildDialog.setTabOrder(self.workDistance_lineEdit, self.area_lineEdit)
        ChildDialog.setTabOrder(self.area_lineEdit, self.timeRatio_lineEdit)
        ChildDialog.setTabOrder(self.timeRatio_lineEdit, self.distanceRatio_lineEdit)
        ChildDialog.setTabOrder(self.distanceRatio_lineEdit, self.ratio_lineEdit)
        ChildDialog.setTabOrder(self.ratio_lineEdit, self.edgeMap_button)
        ChildDialog.setTabOrder(self.edgeMap_button, self.workMap_button)

    def retranslateUi(self, ChildDialog):
        _translate = QtCore.QCoreApplication.translate
        ChildDialog.setWindowTitle(_translate("ChildDialog", "Dialog"))
        self.label.setText(_translate("ChildDialog", "总工作时长(s)："))
        self.label_2.setText(_translate("ChildDialog", "有效工作时长(s)："))
        self.label_3.setText(_translate("ChildDialog", "总工作行程(m)："))
        self.label_4.setText(_translate("ChildDialog", "有效工作行程(m)："))
        self.label_5.setText(_translate("ChildDialog", "作业面积（m^2)："))
        self.label_6.setText(_translate("ChildDialog", "时间利用率："))
        self.label_7.setText(_translate("ChildDialog", "行程率："))
        self.label_8.setText(_translate("ChildDialog", "单位时间内的作业面积:"))
        self.edgeMap_button.setText(_translate("ChildDialog", "显示底图"))
        self.workMap_button.setText(_translate("ChildDialog", "显示工作点"))
        self.traMap_button.setText(_translate("ChildDialog", "显示路径"))

